
CREATE TABLE NHANVIEN
(
	MANHANVIEN CHAR(10) PRIMARY KEY,
	HO VARCHAR(30),
	TEN VARCHAR(30),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	DIENTHOAI VARCHAR(11) UNIQUE,
	LUONGCOBAN MONEY CHECK (LUONGCOBAN > 0),
	PHUCAP MONEY CHECK (PHUCAP > 0)
)
