CREATE TABLE CHITIETDATHANG 
(
    SOHOADON CHAR(5),
    MAHANG CHAR(5),
    GIABAN FLOAT CHECK (GIABAN > 0),
    SOLUONG INT CHECK (SOLUONG > 0),
    MUCGIAMGIA FLOAT CHECK (MUCGIAMGIA > 0),
    PRIMARY KEY (SOHOADON, MAHANG)
);
