CREATE TABLE NHACUNGCAP 
(
    MACONGTY	CHAR(10) PRIMARY KEY,
    TENCONGTY	NVARCHAR(30),
    TENGIAODICH NVARCHAR(30),
    DIACHI		NVARCHAR(40),
    DIENTHOAI	VARCHAR(10),
    FAX			VARCHAR(10),
    EMAIL		VARCHAR(20)
);